import React from 'react'
import "./About.css"

const About = () => {
  return (<>
    <div>About</div>
    <p className='error'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam optio magni, mollitia nostrum minus amet tempore! Alias esse tenetur vitae facilis quisquam accusamus quidem quam natus ducimus. Asperiores placeat itaque debitis dolorum corporis nesciunt tenetur a! Dicta placeat cum, dolorem consequatur soluta similique! Quas unde, eius voluptatem necessitatibus libero magni! Voluptatem deserunt repellendus nemo nam, ipsum sunt. Animi dolorum possimus a? Modi voluptatum ut perferendis sit delectus cumque at reiciendis porro possimus nesciunt! Eaque non quibusdam ducimus a maiores repudiandae corrupti natus ratione fugit iure voluptatum qui molestiae, adipisci beatae cupiditate obcaecati ipsa? Beatae iste doloribus officiis eius veniam voluptates dicta reiciendis ex modi temporibus. Vitae quisquam asperiores nobis facilis, repellendus expedita odit eum voluptate corrupti sunt facere non inventore possimus exercitationem neque. Placeat, nihil quisquam dicta modi numquam nisi reiciendis magni porro maiores quas laborum voluptates nesciunt a, quos temporibus voluptate aut minima reprehenderit harum, nulla quod. Quis expedita ut sapiente rem nam hic esse reprehenderit tempore alias nisi harum laborum distinctio porro fugiat dolorem natus autem, consequuntur exercitationem. Eum eligendi excepturi recusandae laborum corrupti. Alias at rem porro optio et officiis doloribus nostrum non magnam placeat. Cupiditate repellendus vel nesciunt eum eaque veritatis, maiores nemo earum dolor cum, nisi odio doloremque? Nulla sunt eligendi cupiditate, excepturi iure totam id fugit perferendis. Temporibus ipsa corrupti, quibusdam vitae deserunt voluptatibus et laborum, minus ad id non cupiditate aut tempore cum autem hic culpa est similique officia! Minima fuga eos dignissimos, quae quia totam repellendus expedita praesentium placeat. Laborum laudantium dicta corrupti facilis iure modi doloribus, dolorem perspiciatis quis eum, alias consectetur repellendus saepe inventore voluptate mollitia, culpa nam dolorum in officiis quo at sequi aut unde. Eligendi optio libero saepe, reiciendis rerum asperiores doloribus cupiditate excepturi ex facilis cum enim, temporibus id aut ipsa omnis nulla minima consequatur? Nihil, officiis!</p>
  </>)
}

export default About